# ────────────────────────────────────────────────────────
# CI + CD: Test → Build → Push to Docker Hub → Deploy to Railway
# ────────────────────────────────────────────────────────
name: CI-CD | Build & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# ────────────────────────────────────────────────────────
# Global environment
# ────────────────────────────────────────────────────────
env:
  # Docker image name in Docker Hub (username is injected from secrets)
  DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/hand-gesture-api # Updated repo name for clarity

  # Railway deployment variables (set as Repository Variables in GitHub)
  RAILWAY_PROJECT: ${{ vars.RAILWAY_PROJECT_ID }} # Your Railway Project ID
  RAILWAY_SERVICE: ${{ vars.RAILWAY_SERVICE_NAME }} # Your Railway Service Name (e.g., 'hand-gesture-api-service')

  # Toggle: 'true'  ➜ build + push only
  #          'false' ➜ full deploy to Railway
  DRY_RUN:           ${{ vars.DRY_RUN || 'true' }} # Default to 'true' for safety

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for Google Cloud if you were using it, but good to keep for general OIDC

    steps:
    # ────────────────────────────────
    # 1. Check out repository
    # ────────────────────────────────
    - uses: actions/checkout@v4

    # ────────────────────────────────
    # 2. Python setup + dependencies
    # ────────────────────────────────
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10" # Use a Python version consistent with your Dockerfile and requirements.txt

    - name: Install deps & run tests
      run: |
        python -m pip install --quiet --upgrade pip
        pip install -q -r requirements.txt
        python -m pytest tests/ # Uncommented to run your tests

    # ────────────────────────────────
    # 3. Login to Docker Hub
    # ────────────────────────────────
    - name: Docker Hub – login
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" \
          | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    # ────────────────────────────────
    # 4. Build image and push both :<SHA> and :latest tags
    # ────────────────────────────────
    - name: Build & push image
      env:
        TAG: ${{ github.sha }}
      run: |
        # Build once, attach two tags
        docker build \
          -t $DOCKERHUB_REPO:$TAG \
          -t $DOCKERHUB_REPO:latest \
          . # Changed context from ./app to . assuming Dockerfile is in root

        # Push both tags
        docker push $DOCKERHUB_REPO:$TAG
        docker push $DOCKERHUB_REPO:latest

        # Expose the immutable tag to later steps
        echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

    # ────────────────────────────────
    # 5. Install Railway CLI (skipped if DRY_RUN)
    # ────────────────────────────────
    - name: Install Railway CLI
      if: env.DRY_RUN == 'false'
      run: |
        npm install -g @railwaydev/cli # Railway CLI is a Node.js package

    # ────────────────────────────────
    # 6. Authenticate to Railway (skipped if DRY_RUN)
    # ────────────────────────────────
    - name: Railway – login
      if: env.DRY_RUN == 'false'
      run: |
        railway login --token ${{ secrets.RAILWAY_TOKEN }}

    # ────────────────────────────────
    # 7. Deploy to Railway (skipped if DRY_RUN)
    # ────────────────────────────────
    - name: Deploy to Railway
      if: env.DRY_RUN == 'false'
      run: |
        # Use the specific image tag (SHA) for deployment
        railway deploy \
          --service ${{ env.RAILWAY_SERVICE }} \
          --project ${{ env.RAILWAY_PROJECT }} \
          --image ${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_TAG }}
